# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitems',
            name='bucketlist',
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='list_items',
            field=models.ManyToManyField(to='bucket.ListItems'),
        ),
    ]
